theme: jekyll-theme-minimal
title: "Reddit's Invisible Brain: The Web Hidden Beneath the Threads"
description: "A template website for ADA"
show_downloads: false
navigation:
  - title: Home
    url: /
  - title: Example
    url: /example